### ISSUE TITLE
client_password shows in Terraform plan

### ISSUE THREAD

**Issue by Shinseina** [dome9/terraform-provider-dome9#39]
It looks like the client_password (Azure app secret) is showing up in the Terraform plan. This has been verified for Azure, but have not tested on AWS or GCP. Thinking this is a bug but wanted to flag either way.

**Comment by talsheldon** [comment]
Hi @Shinseina, 

Thanks for helping us to improve our provider! 
We fixed it  (#40),  and it will be released in the next version release.

**Comment by nataliapiasek** [comment]
Hi @talsheldon,
We started using release 1.14 but unfortunately client_password is still showing in Terraform plan. Any chance you could have a look at it again?

```2019-12-13T12:38:08.433Z [INFO]  plugin.terraform-provider-dome9_v1.14.0_x4: [INFO] initialized Dome9 client ```
